name: Publish Python Package

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install build tools
        run: pip install build twine

      - name: Build package
        run: python -m build

      - name: Publish to GitHub Packages
        run: |
          twine upload \
            --repository-url https://upload.pypi.org/legacy/ \
            -u ${{ github.actor }} \
            -p ${{ secrets.GH_PUBLISH_TOKEN }} \
            dist/*
