name: Run BasePJT

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Show repository tree (debug)
        run: ls -R .

      - name: Fix permissions
        run: chmod +x scripts/run.sh

      - name: Run project
        run: bash scripts/run.sh
